name: Hello World Action

on:
  workflow_dispatch:
jobs:
  Say-Hello-World:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello World"
      - name: Say Goodbye
        run: echo "Goodbye World"
  Python-Job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Python Version
        run: |
          import sys
          print("Python version:", sys.version)
        shell: python
